### ISSUE TITLE
java.lang.NullPointerException in ShapeMouseHandler.mouseDragged

### ISSUE THREAD

**Issue by leanne63** [kbmaz/Java-Samples#1]
I'm able to successfully draw a rectangle, say; however, when I attempt to move the rectangle, eclipse spouts out a java.lang.NullPointerException exception:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at
event.ShapeMouseHandler.mouseDragged(ShapeMouseHandler.java:119)

Your code from line 115 - 122 of ShapeMouseHandler.java is:

```
if(model.getAction() == Model.MOVE) {
     //shape = model.returnSelectShape(e.getX(), e.getY());
     if(model.getShapeArrayList() != null) {
           shape = model.returnSelectShape(e.getX(), e.getY());
           shape.setX(e.getX());
           shape.setY(e.getY());
     }
}
```

You're checking getShapeArrayList for a null result. That's great! What happens, then, if the ShapeArrayList _isn't_ null - but the model's code doesn't find a matching shape in that array?

Lines 71 - 78 of Model.java:

```
public Shape returnSelectShape(int xClk, int yClk) {
  for(Shape element : shapeArrayList) {
      if(element.containsLocation(xClk, yClk)) {
          return element;
      }
  }
  return null;
}
```

**Comment by kbmaz** [comment]
I don't know.  I'm very stuck on this problem.  I go around and around with my professor.  He's telling me I don't setX or setY.  I don't know what else to do.

**Comment by leanne63** [comment]
Well, it's setting X and Y - _if_ the shape exists. If the shape is null, however, your program is crashing. Try something like this in ShapeMouseHandler.java:

```
if(model.getAction() == Model.MOVE) {
 if(model.getShapeArrayList() != null) {
       shape = model.returnSelectShape(e.getX(), e.getY());
       if (shape != null) {
           shape.setX(e.getX());
           shape.setY(e.getY());
       }
 }
}
```

This code example, of course, is assuming that you set X and Y if the shape is found in the array, and that you don't need to do anything if the shape is not found in the array (meaning _null_ is returned from model.returnSelectShape). If there's something you need to do if the shape is not found in the array, then you'll need to add an _else_ to handle that situation.

**Comment by kbmaz** [comment]
This is getting me closer, I can move the last shape created using this
code:

if(modelgetAction() == Model.MOVE) {
  if(model.getShapeArrayList() != null) {
    if(shape != null) {
      model.getShapeArrayList();
      shape = model.returnSlectShape(e.getX(), e.getY());
    }
  }
}

How can I get it to allow me to move any shape I click on?

**Comment by leanne63** [comment]
This is interesting code. You need to think carefully about what it is doing. For example, what is the line:

```
model.getShapeArrayList();
```

doing? It appears to me that it is retrieving the shape arraylist - but, it's not putting the results of the call anywhere, so you're not actually using it. That is, unless the _getShapeArrayList_ function has a "side effect" - meaning it does something that affects the code somewhere (say a global variable), but doesn't need to return any specific value. You are using it in the 2nd _if_, though, with a value, so does it both return a value _AND_ have a side effect???

So, here's a line-by-line breakdown from the beginning of this code snippet:

```
if(modelgetAction() == Model.MOVE) {
```

If the _modelgetAction_ function returns MOVE (the user is trying to move the shape, yes?)...

```
if(model.getShapeArrayList() != null) {
```

and, if the model's _getShapeArrayList_ function returns something (some shape(s) have been added to the arraylist, yes? Though, we don't know at this point if it's the shape the user is trying to move)...

```
if(shape != null) {
```

and, if _shape_ exists...  Oops! Wait a minute! Where are we getting _shape_ from???

Further down, you're getting a _shape_ returned from model's _returnSelectShape_ method; but we can't use that at this point. Do we have _shape_ defined earlier, before the first _if_ in this code block?

What happened when you tried my example code a couple of comments above?

**Comment by kbmaz** [comment]
The earlier code didn't move anything. It didn't give me errors either, but it didn't move anything.

**Comment by kbmaz** [comment]
So, if I check for != null in shapeArrayList and shape, then will I want to
say something liek:

if(model.getAction() == Model.MOVE){
of(model.getShapeArrayList() != null){
if(shape != null) {
[i] = 0; //initialize the array or do I run through a for loop to find the
selected shape?
shape = shapeArrayList.get(i);  //to select a shape that I've drawn and then
shape = model.returnSelectShape(e.getX(), e.getY()); //to move selected
shape
}
}
}

**Comment by leanne63** [comment]
kmaz successfully corrected the original code and completed the project.
